// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcnddvmkmehgapazbxlj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjbmRkdm1rbWVoZ2FwYXpieGxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NDQ3ODAsImV4cCI6MjA1OTUyMDc4MH0.4XZ-zSiGE3yZXAbMT2YN3Wti_iXMVC1InG8BeqB_mMk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);